
name: release workflow

on: 
  - push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform-workflow:
    permissions: 
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: sets up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
      - name: releases
        run: npx semantic-release
        env: 
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
     # - name: Terraform apply
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     #   run: terraform apply -auto-approve
     # - name: Terraform destroy
     #   run: terraform destroy -auto-approve
           
        