name: shell commands

on: 
  - push

env:
  AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Multi-line string
        run: |
           pwd
           ls -a
  terraform workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: sets up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
     # - name: Terraform apply
     #   run: terraform apply
     # - name: Terraform destroy
     #   run: terraform destroy
           
        